# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_creators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreator',
            name='note',
            field=models.CharField(blank=True, help_text='Anotaciones opcionales sobre este usuario (por ejemplo, por que se deneg\xf3 el acceso a la creaci\xf3n de cursos)', max_length=512),
        ),
        migrations.AlterField(
            model_name='coursecreator',
            name='state',
            field=models.CharField(choices=[(b'unrequested', 'No solicitado'), (b'pending', 'pendiente'), (b'granted', 'concedido'), (b'denied', 'denegado')], default=b'unrequested', help_text='Estado del creador del curso actual', max_length=24),
        ),
        migrations.AlterField(
            model_name='coursecreator',
            name='state_changed',
            field=models.DateTimeField(auto_now_add=True, help_text='\xdaltima fecha de actualizaci\xf3n del estado', verbose_name=b'state last updated'),
        ),
        migrations.AlterField(
            model_name='coursecreator',
            name='user',
            field=models.OneToOneField(help_text='Usuario de Studio', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
