# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_delete_historical_credit_records'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditrequirementstatus',
            options={'verbose_name_plural': 'Estados de requerimientos para cr\xe9ditos'},
        ),
        migrations.AlterField(
            model_name='creditconfig',
            name='cache_ttl',
            field=models.PositiveIntegerField(default=0, help_text='Especificado en segundos. Habilite el cache configurando este campo en un valor mayor que 0.', verbose_name='Tiempo de vida del Cache'),
        ),
    ]
